[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nandseqgen"
version = "0.1.0"
description = "A NAND sequence generator project"
dependencies = [
    "PyYAML",
    "numpy"
]
